module "mongodb" {
  source = "./vendor/modules/mongodb"
  ENV = var.ENV
  WORKSTATION_IP = var.WORKSTATION_IP
  DOCTDB_PORT = var.DOCTDB_PORT
  DOCDB_INSTANCE_CLASS = var.DOCDB_INSTANCE_CLASS
  DOCDB_INSTANCE_COUNT = var.DOCDB_INSTANCE_COUNT

}

module "redis" {
  source = "./vendor/modules/redis"
  ENV = var.ENV
  ELASTICACHE_PORT = var.ELASTICACHE_PORT
  ELASTICACHE_NODE_TYPE = var.ELASTICACHE_NODE_TYPE
  ELASTICACHE_NODE_COUNT = var.ELASTICACHE_NODE_COUNT
  ELASTICACHE_ENGINE_VERSION = var.ELASTICACHE_ENGINE_VERSION
}

module "mysql" {
  source = "./vendor/modules/mysql"
  ENV = var.ENV
  WORKSTATION_IP = var.WORKSTATION_IP
  RDS_MYSQL_PORT = var.RDS_MYSQL_PORT
  RDS_MYSQL_STORAGE = var.RDS_MYSQL_STORAGE
  RDS_ENGINE_VERSION = var.RDS_ENGINE_VERSION
  RDS_INSTANCE_TYPE = var.RDS_INSTANCE_TYPE
}

module "rabbitmq" {
  source = "./vendor/modules/rabbitmq"
  ENV = var.ENV
  RABBITMQ_PORT = var.RABBITMQ_PORT
  RABBITMQ_ENGINE_VERSION = var.RABBITMQ_ENGINE_VERSION
  RABBITMQ_INSTANCE_TYPE = var.RABBITMQ_INSTANCE_TYPE

}

output "data" {
  value = module.mongodb.data
}
