ENV = "dev"
WORKSTATION_IP = "172.31.85.160/32"

#RDS_MYSQL
RDS_MYSQL_PORT = 3306
RDS_MYSQL_STORAGE = 10
RDS_ENGINE_VERSION = "5.7"
RDS_INSTANCE_TYPE = "db.t3.micro"

#DOCDB
DOCTDB_PORT = 27017
DOCDB_INSTANCE_CLASS = "db.t3.medium"
DOCDB_INSTANCE_COUNT = 1

#RABBITMQ
RABBITMQ_PORT = 5672
RABBITMQ_ENGINE_VERSION = "3.9.13"
RABBITMQ_INSTANCE_TYPE = "mq.t3.micro"

#REDIS
ELASTICACHE_PORT = 6379
ELASTICACHE_NODE_TYPE = "cache.t3.small"
ELASTICACHE_NODE_COUNT = 1
ELASTICACHE_ENGINE_VERSION = "6.x"